<div class="container">
    <h1>Liste des Villes</h1>
    <button type="button" class="btn btn-outline-dark"><a href="create.php">Ajouter une nouvelle ville <i class="far fa-plus-square"></i></a></button>
    <table id='example'>
        <thead>
            <?php foreach ($cities[0] as $key => $city) { ?>

                <th><?php echo $key   ?></th>

            <?php } ?>
            <th>Modifier</th>
        </thead>
        <tbody>
            <?php foreach ($cities as $city) { ?>
                <tr> <?php foreach ($city as $key => $value) { ?>

                        <td><?php echo $value; ?></td>

                    <?php } ?>
                    <td> <a href="../crudCity/update.php?id=<?php echo $city->id ?>"><i class="far fa-edit"></i></a>
                        <a href="../crudCity/delete.php?id=<?php echo $city->id ?>"> <i class="far fa-trash-alt"></i> </a></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>