<form method="post">

    <?php if (isset($city)) { ?>
        <h1>Editer la ville : <?php echo $city->name ?> </h1>
        <label for="id"> id</label>
        <input type="text" name="id" id="id" value="<?= isset($city) ? $city->id : '' ?>">
    <?php } else { ?>
        <h1>Creer une nouvelle ville </h1>
    <?php } ?>
    <label for="name"> name</label>
    <input type="text" name="name" id="name" value="<?= isset($city) ? $city->name : '' ?>">
    <label for="countryCode"> Code pays </label>
    <select name="countryCode" id="countryCode">

        <?php foreach ($countries as $country) { ?>

            <option value="<?php echo $country->code ?>"><?php echo $country->name ?></option>

        <?php } ?>
    </select>
    <label for="district"> district</label>
    <input type="text" name="district" id="district" value="<?= isset($city) ? $city->district : '' ?>">
    <label for="population"> population</label>
    <input type="number" name="population" id="population" value="<?= isset($city) ? $city->population : '' ?>">
    <input type="submit" value="modifier">
</form>